/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('../components/Layout/UserAvatar.vue')['default']
    BaseUpload: typeof import('./../components/BaseUpload.vue')['default']
    copy: typeof import('../components/Modules/Create/ModulesCreateModalSelect.vue')['default']
    Flag: typeof import('./../components/Flag.vue')['default']
    ModuleCheckbox: typeof import('./../components/Modules/View/ModuleCheckbox.vue')['default']
    ModuleCover: typeof import('./../components/Modules/View/ModuleCover.vue')['default']
    ModuleDescription: typeof import('./../components/Modules/View/ModuleDescription.vue')['default']
    ModuleLanguages: typeof import('./../components/Modules/View/ModuleLanguages.vue')['default']
    ModuleOverview: typeof import('./../components/Modules/View/ModuleOverview.vue')['default']
    ModuleProgress: typeof import('../components/Modules/ModulesProgress.vue')['default']
    ModulesCard: typeof import('./../components/Modules/List/ModulesCard.vue')['default']
    ModulesCardSkeleton: typeof import('./../components/Modules/List/ModulesCardSkeleton.vue')['default']
    ModulesCreateCard: typeof import('./../components/Modules/List/ModulesCreateCard.vue')['default']
    ModulesCreateModal: typeof import('./../components/Modules/Create/ModulesCreateModal.vue')['default']
    ModulesCreateModalInput: typeof import('./../components/Modules/Create/ModulesCreateModalInput.vue')['default']
    ModuleShortDescription: typeof import('./../components/Modules/View/ModuleShortDescription.vue')['default']
    ModulesProgress: typeof import('./../components/Modules/List/ModulesProgress.vue')['default']
    ModulesSection: typeof import('./../components/Modules/List/ModulesSection.vue')['default']
    ModulesSectionTitle: typeof import('./../components/Modules/List/ModulesSectionTitle.vue')['default']
    ModulesStat: typeof import('./../components/Modules/ModulesStat.vue')['default']
    ModuleTabs: typeof import('./../components/Modules/View/ModuleTabs.vue')['default']
    ModuleThumbnail: typeof import('./../components/Modules/View/ModuleThumbnail.vue')['default']
    ModuleThumbnailModal: typeof import('./../components/Modules/View/ModuleThumbnailModal.vue')['default']
    ModuleTime: typeof import('./../components/Modules/View/ModuleTime.vue')['default']
    NavBar: typeof import('./../components/Layout/NavBar/NavBar.vue')['default']
    NavIcon: typeof import('./../components/Layout/NavBar/NavIcon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsBar: typeof import('./../components/Layout/SettingsBar.vue')['default']
    UserAvatar: typeof import('./../components/Layout/UserAvatar.vue')['default']
    WelcomeBanner: typeof import('./../components/Modules/List/WelcomeBanner.vue')['default']
  }
}
